server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rodman129
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db-liq/liquibase-changeLog.xml
